[project]
authors = ["neverorfrog <97flavio.maiorana@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ismpc_cpp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
main = "python bindings/main.py"
build-cpp = 'mkdir -p build && cd build && cmake .. && cmake --build . -j12'
main-cpp = './build/executables/ismpc_main'
main-dart = './build/executables/dart_main'
build = 'python setup.py build'
install = 'python setup.py install'

[dependencies]
python = "==3.11"
matplotlib = ">=3.9.3,<4"
pyyaml = ">=6.0.2,<7"
omegaconf = ">=2.3.0,<3"
numpy = ">=2.2.0,<3"
tqdm = ">=4.67.1,<5"
setuptools = ">=75.6.0,<76"
