[project]
authors = ["neverorfrog <97flavio.maiorana@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "intrinsically-stable-mpc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.build]
cmd = "mkdir -p build && cd build && cmake .. && cmake --build . -j12"

[tasks.main]
cmd = "./build/executables/ismpc_main"

[tasks.tests]
cmd = "GTEST_COLOR=1 ctest -V --test-dir build/test --output-on-failure -j13"

[dependencies]
