[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies] 
ismpc = { path = "." }
python = "3.11.*"

[package] 
name = "ismpc"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.1.*" } 

[package.build.configuration]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"] 

[package.host-dependencies]
cmake = "3.20.*"
nanobind = "2.4.*"
python = "3.11.*"
eigen = ">=3.4.0,<4"
simde = ">=0.8.0,<1"
yaml-cpp = ">=0.8.0,<0.9"

# [tasks]
# preinstall = 'sudo apt install libeigen3-dev && sudo apt install libsimde-dev'
# build = 'mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . -j$(nproc)'
# build-debug = 'mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . -j$(nproc)'
# main = './build/executables/ismpc_main'