[project]
authors = ["neverorfrog <97flavio.maiorana@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ismpc_cpp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
preinstall = 'sudo apt install libeigen3-dev && sudo apt install libsimde-dev'
build = 'mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . -j12'
build-debug = 'mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . -j12'
main = './build/executables/ismpc_main'
