save_log: false

# Time step for simulation [s]
delta: 0.01205 # 83 Hz
fs_duration: 0.35 # [s]
nl: 1

# Duration parameters
N: 1000
P: 60
C: 60

# Which robot to simulate
robot: nao

# Input Velocities
des_vel_x: 0.1 # [m/s]
des_vel_y: 0.0 #  [m/s]
des_omega: 0.0 #  [rad/s]

# Tail: PERIODIC, TRUNCATED, or ANTICIPATIVE
tail_type: PERIODIC
