save_log: false

# Time step for simulation [s]
delta: 0.01 # 83 Hz
fs_duration: 0.6 # [s]
nl: 1

# Duration parameters
N: 1001
P: 400
C: 100

# Which robot to simulate
robot: hrp4

# Input Velocities
des_vel_x: 0.15 # [m/s]
des_vel_y: 0.0 #  [m/s]
des_omega: 0.0 #  [rad/s]

# Tail: PERIODIC, TRUNCATED, or ANTICIPATIVE
tail_type: PERIODIC
