name: Build and Upload Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Create wheelhouse directory
        run: mkdir -p wheelhouse

      - name: Build wheel
        run: |
          sudo docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 /bin/bash -c "
            yum install -y epel-release &&
            yum-config-manager --add-repo=https://download.opensuse.org/repositories/science:/dlr/CentOS_7/ &&
            yum install -y --nogpgcheck eigen3-devel &&
            cd /usr/local/include &&
            curl -L https://github.com/simd-everywhere/simde/archive/refs/heads/master.zip -o simde.zip &&
            unzip simde.zip &&
            mv simde-master/simde . &&
            rm -rf simde.zip simde-master &&
            cd /io &&
            /opt/python/cp311-cp311/bin/pip install setuptools wheel --root-user-action=ignore &&
            /opt/python/cp311-cp311/bin/python setup.py bdist_wheel &&
            auditwheel repair dist/ismpc-0.1-cp311-cp311-linux_x86_64.whl --plat manylinux2014_x86_64 && 
            chown -R $(id -u):$(id -g) /io/wheelhouse"

      - name: Upload wheels to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
        run: |
          python -m pip install --upgrade twine &&
          twine upload --verbose wheelhouse/*.whl