name: Build Wheel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Run wheel script
      run: |
        sudo docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 /bin/bash -c "
          yum install -y epel-release &&
          yum-config-manager --add-repo=https://download.opensuse.org/repositories/science:/dlr/CentOS_7/ &&
          yum install -y --nogpgcheck eigen3-devel &&
          cd /usr/local/include &&
          curl -L https://github.com/simd-everywhere/simde/archive/refs/heads/master.zip -o simde.zip &&
          unzip simde.zip &&
          mv simde-master/simde . &&
          rm -rf simde.zip simde-master &&
          cd /io &&
          /opt/python/cp311-cp311/bin/pip install setuptools wheel &&
          /opt/python/cp311-cp311/bin/python setup.py bdist_wheel &&
          auditwheel repair dist/ismpc-0.1-cp311-cp311-linux_x86_64.whl --plat manylinux2014_x86_64"